import * as esbuild from 'esbuild';
import { cpSync, mkdirSync, copyFileSync, readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join, resolve } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rendererDir = resolve(__dirname, '../app/renderer');
const distDir = resolve(__dirname, 'dist');
const watch = process.argv.includes('--watch');

// Ensure dist/ exists
mkdirSync(distDir, { recursive: true });

// Copy static assets from app/renderer/ into dist/
const dirs = ['acesrc', 'photon', 'ink-icons', 'img'];
for (const d of dirs) {
    cpSync(join(rendererDir, d), join(distDir, d), { recursive: true, force: true });
}
const files = ['main.css', 'inkTheme.css', 'dark.css', 'contrast.css', 'focus.css'];
for (const f of files) {
    copyFileSync(join(rendererDir, f), join(distDir, f));
}
// Files in web/ (not renderer) copied to dist/
copyFileSync(join(__dirname, 'index.html'),     join(distDir, 'index.html'));
copyFileSync(join(__dirname, 'web.css'),        join(distDir, 'web.css'));
copyFileSync(join(__dirname, 'favicon-32.png'), join(distDir, 'favicon-32.png'));
copyFileSync(join(__dirname, 'favicon-180.png'), join(distDir, 'favicon-180.png'));

// Export-for-web player template: copied into dist/export-template/ so the
// bundle can fetch them at runtime without bundling large static assets.
const exportTemplateDir = resolve(__dirname, '../app/export-for-web-template');
const exportDistDir     = join(distDir, 'export-template');
mkdirSync(exportDistDir, { recursive: true });
for (const f of ['index.html', 'main.js', 'style.css']) {
    copyFileSync(join(exportTemplateDir, f), join(exportDistDir, f));
}
copyFileSync(
    resolve(__dirname, 'node_modules/inkjs/dist/ink.js'),
    join(exportDistDir, 'ink.js')
);

console.log('Assets copied.');

// Generate web-snippets-generated.js by inlining longer .ink snippet files
(function generateSnippets() {
    const snippetsDir = resolve(__dirname, '../app/main-process/ink/longer-ink-snippets');
    const names = [
        'a_or_an', 'came_from', 'list_item_is_member_of', 'list_pop', 'list_pop_random',
        'list_prev_next', 'list_random_subset', 'list_random_subset_of_size', 'listToNumber',
        'list_with_commas', 'maybe', 'murder_scene', 'pontoon_example', 'print_number',
        'seen_more_recently_than', 'seen_this_scene', 'seen_very_recently', 'storylets',
        'string_to_list', 'swindlestones', 'swing_variables', 'thread_in_tunnel',
        'type_of', 'uppercase',
    ];
    const data = {};
    for (const n of names) data[n] = readFileSync(join(snippetsDir, n + '.ink'), 'utf8') + '\n';
    writeFileSync(
        join(__dirname, 'web-snippets-generated.js'),
        '// Auto-generated by build.mjs — do not edit manually\nmodule.exports = ' +
        JSON.stringify(data) + ';\n'
    );
    console.log('Snippets generated.');
})();

const shimDir = resolve(__dirname, 'shims');

// Plugin: redirect relative liveCompiler.js imports to our web version.
// inkProject.js does require('./liveCompiler.js') which we must intercept.
const replaceRelativeModules = {
    name: 'web-replacements',
    setup(build) {
        build.onResolve({ filter: /\/liveCompiler\.js$/ }, () => ({
            path: resolve(__dirname, 'web-liveCompiler.js'),
        }));
    },
};

const buildOptions = {
    entryPoints: [resolve(__dirname, 'web-controller.js')],
    bundle: true,
    outfile: join(distDir, 'bundle.js'),
    platform: 'browser',
    format: 'iife',
    plugins: [replaceRelativeModules],
    alias: {
        'electron':  join(shimDir, 'electron.js'),
        'path':      join(shimDir, 'path.js'),
        'fs':        join(shimDir, 'fs.js'),
        'chokidar':  join(shimDir, 'chokidar.js'),
        'mkdirp':    join(shimDir, 'mkdirp.js'),
        'assert':    join(shimDir, 'assert.js'),
        'buffer':    join(shimDir, 'buffer.js'),
    },
    // Look for npm packages in web/node_modules (e.g. lodash, inkjs)
    nodePaths: [resolve(__dirname, 'node_modules')],
    define: {
        'process.platform': '"web"',
        'process.env.NODE_ENV': '"production"',
    },
    banner: {
        js: [
            // setImmediate is Node-only
            'if(typeof setImmediate==="undefined")window.setImmediate=function(fn,_a,_b){return setTimeout(fn,0);};',
            // scrollIntoViewIfNeeded is Chrome/Electron-only (used in navView.js)
            'if(!Element.prototype.scrollIntoViewIfNeeded)Element.prototype.scrollIntoViewIfNeeded=function(c){this.scrollIntoView({block:c===false?"end":"nearest"});};',
        ].join(''),
    },
    logLevel: 'info',
};

if (watch) {
    const ctx = await esbuild.context(buildOptions);
    await ctx.watch();
    console.log('Watching for changes… (Ctrl+C to stop)');
} else {
    await esbuild.build(buildOptions);
    console.log('Build complete → dist/');
}
